### ISSUE TITLE
Crash on recording.pause() for windows

### ISSUE THREAD

**Issue by qduborper** [gillesdemey/node-record-lpcm16#55]
Hello ! I'm using node 12 on windows, and when I run the google speech microphone stream example (https://github.com/googleapis/nodejs-speech/blob/master/samples/MicrophoneStream.js), then do a pause after 2 seconds, I got this error

`TypeError [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGSTOP
    at convertToValidSignal (internal/util.js:228:9)
    at ChildProcess.kill (internal/child_process.js:422:5)
    at Recording.pause (******\node_modules\node-record-lpcm16\index.js:81:18)
    at Timeout.setTimeout [as _onTimeout] (******\server.js:78:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

Any idea ? 
thank you

**Comment by LingleDev** [comment]
I'm getting this error also

**Comment by tingyang01** [comment]
Hello
I am getting the same error too.
